services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Australia/Melbourne
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
    volumes:
      - ./config/server:/app/server
      - ./config:/app/configs
      - ./config/logs:/app/logs
      - /mnt/lab_data/tvseries:/media/tvseries
      - /mnt/lab_data/movies:/media/movies
      - /tmp/tdarr:/temp

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=MainNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - ./config:/app/configs
      - ./config/logs:/app/logs
      - /mnt/lab_data/tvseries:/media/tvseries
      - /mnt/lab_data/movies:/media/movies
      - /tmp/tdarr:/temp

networks:
  default:
    name: main_net
    external: true
