services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host 
    environment:
      - PUID=1000 
      - PGID=1000 
      - SUBDOMAINS=${HOST}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4 
      - LOG_FILE=false 
    volumes:
      - ./config:/config 
    restart: unless-stopped