services:
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 784:784/udp
            - 853:853/tcp
            - 3023:3000/tcp
            - 83:80/tcp
            - 8180:8180
        volumes:
            - ./config/work:/opt/adguardhome/work
            - ./config/conf:/opt/adguardhome/conf

networks:
  default:
    name: main_net
    external: true