services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    restart: unless-stopped
    container_name: pufferpanel
    ports:
      - "8080:8080"
      - "5657:5657"
    volumes:
      - ./config:/etc/pufferpanel
      - /mnt/lab_data/Pufferpanel:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: main_net
    external: true
