---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services
- Stats:
    - CPU Usage:
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_IP}}
            metric: cpu
            version: 4
    - RAM Usage:
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_IP}}
            metric: memory
            version: 4
    - Disk Usage:
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_IP}}
            metric: fs:/mnt/lab_data
            version: 4
    - Disk I/O (1TB):
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_IP}}
            metric: disk:sda
            version: 4
    - Disk I/O (2TB):
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_IP}}
            metric: disk:sdc
            version: 4
    - Network Usage:
        widget:
            type: glances
            url: {{HOMEPAGE_VAR_GLANCES_IP}}
            metric: network:enp6s18
            version: 4

- Media:
    - Immich:
        href: https://immich.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Self-hosted photo and video backup
        server: local_docker
        container: immich_server
        widget:
            type: immich
            url: http://immich_server:3001
            key: {{HOMEPAGE_VAR_IMMICH_KEY}}
    - Radarr:
        href: https://radarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Movie tracking
        server: local_docker
        container: radarr
        widget:
            type: radarr
            url: http://radarr:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - Sonarr:
        href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Series tracking
        server: local_docker
        container: sonarr
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - JellyFin:
        href: https://jellyfin.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Media server
        server: local_docker
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
    - Jellyseerr:
        href: https://jellyseerr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Media ticket server
        server: local_docker
        container: jellyseerr
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: {{HOMEPAGE_VAR_JELLYSEERR_KEY}}
- Utility:
    - Portainer:
        href: https://portainer.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Containers monitoring
        server: local_docker
        container: portainer
        widget:
            type: portainer
            url: https://portainer:9443
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Watchtower:
        href: https://watchtower.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Auto update containers
        server: local_docker
        container: watchtower
        widget:
            type: watchtower
            url: http://watchtower:8080
            key: {{HOMEPAGE_VAR_WATCHTOWER_KEY}}
    - Tdarr:
        href: https://tdarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Local media tracking and transcoding
        server: local_docker
        container: tdarr
        widget:
            type: tdarr
            url: http://tdarr:8265
            key: {{HOMEPAGE_VAR_TDARR_KEY}}
    - Glances:
        href: https://glances.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Resources monitoring
        server: local_docker
        container: glances
        
- Torrent:
    - Qbittorrent:
        href: https://qbittorrent.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Torrent downloader
        server: local_docker
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent:6882
            username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASS}}
    - Prowlarr:
        href: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: RSS indexer
        server: local_docker
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
    - FlareSolverr:
        href: http://flaresolverr:8191
        description: Cloudflare bypass
        server: local_docker
        container: flaresolverr
- Network:
    - AdGuardHome:
        href: https://adguardhome.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Ads block
        server: local_docker
        container: adguardhome
        widget:
            type: adguard
            url: http://adguardhome:3000
            username: {{HOMEPAGE_VAR_ADGUARD_USER}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASS}}
    - Nginx Proxy Manager:
        href: https://{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Proxy manager
        server: local_docker
        container: nginx
        widget:
            type: npm
            url: http://192.168.1.202:81
            username: {{HOMEPAGE_VAR_NGINX_USER}}
            password: {{HOMEPAGE_VAR_NGINX_PASS}}
    - Wireguard:
        href: https://wireguard.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: VPN server
        server: local_docker
        container: wg-easy

