---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Homepage
background:
    image: /images/bg.jpg
cardBlur: xl
theme: dark
headerStyle: boxedWidgets
showStats: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

layout:
  Stats:
    style: row
    columns: 3
  Media:
    style: column
  Utility:
    style: column
  Torrent:
    style: column
  Network:
    style: column
