---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    expanded: true
    disk:
        - /
        - /mnt/lab_data

- search:
    provider: duckduckgo
    target: _blank

- openweathermap:
    label: Melbourne
    latitude: {{HOMEPAGE_VAR_WEATHER_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_WEATHER_LONGITUDE}}
    units: metric 
    provider: openweathermap
    apiKey: {{HOMEPAGE_VAR_WEATHER_KEY}} 
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1