services:
  wg-easy:
    environment:
      - WG_HOST=${HOST}
      - PASSWORD=${PASS}
      - PORT=52000
      - WG_PORT=51000
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      # 1400 or we will get SSL errors when trying to connect to our domain
      # https://www.reddit.com/r/WireGuard/comments/g6whsp/ssh_works_but_https_not/
      - WG_MTU=1400
      - WG_ALLOWED_IPS=192.168.1.0/24, 172.18.0.0/16
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    network_mode: host
    ports:
      - "51000:51000/udp"
      - "52000:52000/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE