services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr            
       environment:
            - PUID=1000
            - PGID=1000
            - LOG_LEVEL=debug
            - TZ=Australia/Melbourne
       ports:
            - 5055:5055
       volumes:
            - ./config:/app/config
       restart: unless-stopped

networks:
  default:
    name: main_net
    external: true
